using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using TccTrafficVision.SumoImport;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace TccTrafficVision.Editor.SumoImport
{
    /// <summary>
    /// Draws the pedestrian infrastructure of Cruzamento.ped.net.xml on top of
    /// the vehicle network imported by Configure SP Visuals: zebra crossings
    /// (SUMO "crossing" edges) and the corner waiting areas ("walkingarea"
    /// edges). Vehicle lanes are identical in both networks and netOffset is
    /// zero, so SUMO coordinates map directly to the scene. Each corner is the
    /// convex hull of its walking area and of the nearby ends of the road
    /// sidewalks generated by the importer (2.4 m wide, while SUMO uses 2 m and
    /// has no sidewalk on some sides), so corners and sidewalks meet without
    /// steps. Only the "SP Pedestrian Infrastructure" root is recreated.
    /// </summary>
    public static class SpPedestrianInfrastructureSetup
    {
        private const string SceneAssetPath = "Assets/Scenes/SPImport.unity";
        private const string RootName = "SP Pedestrian Infrastructure";
        // Read straight from the repository (generated by
        // experiments.build_pedestrian_network) to avoid a second copy.
        private const string PedestrianNetworkPath = "../../sumo/sp/Cruzamento.ped.net.xml";

        // Heights above the road surface (y = 0); lane markings use 0.015-0.025.
        private const float WalkingAreaHeight = 0.01f;
        private const float StripeHeight = 0.02f;
        // Brazilian zebra crossing (CTB/CONTRAN): 0.4 m bars, 0.4-0.6 m gaps.
        private const float StripeWidth = 0.4f;
        private const float StripeGap = 0.5f;
        private const float StripeMargin = 0.3f;
        // Free band between the zebra and the vehicle stop line (road side).
        private const float StopLineClearance = 1.0f;
        // Sidewalk ends closer than this to a walking area join its corner.
        private const float SidewalkJoinDistance = 3.0f;
        private const string GeneratedNetworkName = "GeneratedSumoRoadNetwork";

        [MenuItem("Traffic Vision/Pedestrians/Build SP Crosswalks and Corners")]
        public static void Build()
        {
            Scene scene = SceneManager.GetActiveScene();
            if (scene.path != SceneAssetPath)
            {
                EditorUtility.DisplayDialog(
                    "Open SPImport first",
                    "Open Assets/Scenes/SPImport.unity before building the pedestrian infrastructure.",
                    "OK");
                return;
            }

            string networkPath = Path.GetFullPath(Path.Combine(Application.dataPath, "..", PedestrianNetworkPath));
            if (!File.Exists(networkPath))
            {
                EditorUtility.DisplayDialog(
                    "Pedestrian network missing",
                    $"{networkPath} was not found. Run python -m experiments.build_pedestrian_network first.",
                    "OK");
                return;
            }

            XDocument network = XDocument.Load(networkPath);
            (Material sidewalk, Material marking) = ResolveMaterials();

            GameObject existing = GameObject.Find(RootName);
            if (existing != null)
            {
                Object.DestroyImmediate(existing);
            }

            List<Vector3> sidewalkEnds = CollectSidewalkEnds();
            if (sidewalkEnds.Count == 0)
            {
                Debug.LogWarning($"No road sidewalks found under {GeneratedNetworkName}; corners will not join them. Run Configure SP Visuals first.");
            }

            GameObject root = new GameObject(RootName);
            int corners = 0;
            int crossings = 0;
            foreach (XElement edge in network.Descendants("edge"))
            {
                string function = edge.Attribute("function")?.Value;
                XElement lane = edge.Element("lane");
                if (lane == null)
                {
                    continue;
                }

                List<Vector3> shape = SumoRoadNetworkImporter.ParseShape(lane.Attribute("shape")?.Value, Vector2.zero);
                if (function == "walkingarea" && shape.Count >= 3)
                {
                    List<Vector3> joined = new List<Vector3>(shape);
                    joined.AddRange(sidewalkEnds.Where(end => shape.Min(point => FlatDistance(point, end)) < SidewalkJoinDistance));
                    List<Vector3> lifted = ConvexHull(joined).Select(point => new Vector3(point.x, WalkingAreaHeight, point.z)).ToList();
                    Mesh mesh = SumoRoadNetworkImporter.CreatePolygonMesh(lifted, $"WalkingArea_{edge.Attribute("id")?.Value}");
                    if (mesh != null)
                    {
                        CreateMeshObject($"Corner_{corners++}_{edge.Attribute("id")?.Value}", mesh, sidewalk, root.transform);
                    }
                }
                else if (function == "crossing" && shape.Count >= 2)
                {
                    float width = float.Parse(lane.Attribute("width")?.Value ?? "4", System.Globalization.CultureInfo.InvariantCulture);
                    Vector3 junctionCenter = JunctionCenter(network, edge.Attribute("id")?.Value);
                    Mesh mesh = CreateZebraMesh(shape[0], shape[shape.Count - 1], width, junctionCenter, $"Crossing_{edge.Attribute("id")?.Value}");
                    if (mesh != null)
                    {
                        CreateMeshObject($"Crosswalk_{crossings++}_{edge.Attribute("id")?.Value}", mesh, marking, root.transform);
                    }
                }
            }

            EditorSceneManager.MarkSceneDirty(scene);
            Selection.activeGameObject = root;
            Debug.Log($"Built {crossings} zebra crossings and {corners} pedestrian corners from {networkPath}. Save the scene (Cmd+S).", root);
        }

        /// <summary>
        /// Bars span the crossing width (parallel to the traffic) and repeat
        /// along the walking direction, from one curb to the other. SUMO puts
        /// the crossing right after the end of the vehicle lanes, where the stop
        /// line is drawn, so the bars leave a free band on the side away from
        /// the junction center.
        /// </summary>
        private static Mesh CreateZebraMesh(Vector3 start, Vector3 end, float width, Vector3 junctionCenter, string meshName)
        {
            start.y = 0f;
            end.y = 0f;
            Vector3 along = end - start;
            float length = along.magnitude;
            if (length <= 2f * StripeMargin + StripeWidth)
            {
                return null;
            }

            along /= length;
            Vector3 inward = new Vector3(-along.z, 0f, along.x);
            if (Vector3.Dot(inward, junctionCenter - (start + end) * 0.5f) < 0f)
            {
                inward = -inward;
            }

            // Bars cover [-width/2 + clearance, +width/2] across the crossing,
            // measured towards the junction center.
            float barLength = width - StopLineClearance;
            Vector3 across = inward * (barLength * 0.5f);
            Vector3 shift = inward * (StopLineClearance * 0.5f);
            Vector3 lift = Vector3.up * StripeHeight;
            List<Vector3> vertices = new List<Vector3>();
            List<int> triangles = new List<int>();
            int count = Mathf.FloorToInt((length - 2f * StripeMargin + StripeGap) / (StripeWidth + StripeGap));
            float used = count * StripeWidth + (count - 1) * StripeGap;
            float offset = (length - used) * 0.5f;
            for (int index = 0; index < count; index++)
            {
                Vector3 from = start + shift + along * (offset + index * (StripeWidth + StripeGap)) + lift;
                Vector3 to = from + along * StripeWidth;
                AddUpwardQuad(vertices, triangles, from - across, from + across, to - across, to + across);
            }

            Mesh mesh = new Mesh { name = meshName, vertices = vertices.ToArray(), triangles = triangles.ToArray() };
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            return mesh;
        }

        /// <summary>Center of the junction that owns a crossing (":junction_cN").</summary>
        private static Vector3 JunctionCenter(XDocument network, string crossingId)
        {
            string junctionId = crossingId?.TrimStart(':');
            int suffix = junctionId?.LastIndexOf("_c") ?? -1;
            junctionId = suffix > 0 ? junctionId.Substring(0, suffix) : junctionId;
            XElement junction = network.Descendants("junction").FirstOrDefault(candidate => candidate.Attribute("id")?.Value == junctionId);
            List<Vector3> shape = SumoRoadNetworkImporter.ParseShape(junction?.Attribute("shape")?.Value, Vector2.zero);
            if (shape.Count == 0)
            {
                return new Vector3(
                    float.Parse(junction?.Attribute("x")?.Value ?? "0", System.Globalization.CultureInfo.InvariantCulture), 0f,
                    float.Parse(junction?.Attribute("y")?.Value ?? "0", System.Globalization.CultureInfo.InvariantCulture));
            }

            Vector3 sum = Vector3.zero;
            foreach (Vector3 point in shape)
            {
                sum += point;
            }

            return sum / shape.Count;
        }

        /// <summary>
        /// Both corners (inner and outer) of each end of the road sidewalks
        /// built by SumoRoadNetworkImporter. Each ribbon is a strip of quads
        /// (fromInner, fromOuter, toInner, toOuter), so its ends are the first
        /// two and the last two vertices.
        /// </summary>
        private static List<Vector3> CollectSidewalkEnds()
        {
            List<Vector3> ends = new List<Vector3>();
            GameObject network = GameObject.Find(GeneratedNetworkName);
            if (network == null)
            {
                return ends;
            }

            foreach (MeshFilter filter in network.GetComponentsInChildren<MeshFilter>())
            {
                Vector3[] vertices = filter.sharedMesh != null ? filter.sharedMesh.vertices : null;
                if (!filter.name.StartsWith("Sidewalk_") || vertices == null || vertices.Length < 4)
                {
                    continue;
                }

                foreach (int index in new[] { 0, 1, vertices.Length - 2, vertices.Length - 1 })
                {
                    ends.Add(filter.transform.TransformPoint(vertices[index]));
                }
            }

            return ends;
        }

        /// <summary>Convex hull on the ground plane (Andrew's monotone chain).</summary>
        private static List<Vector3> ConvexHull(IEnumerable<Vector3> points)
        {
            List<Vector3> sorted = points.OrderBy(point => point.x).ThenBy(point => point.z).ToList();
            if (sorted.Count < 3)
            {
                return sorted;
            }

            List<Vector3> hull = new List<Vector3>();
            for (int pass = 0; pass < 2; pass++)
            {
                int start = hull.Count;
                foreach (Vector3 point in sorted)
                {
                    while (hull.Count >= start + 2 && Cross(hull[hull.Count - 2], hull[hull.Count - 1], point) <= 0f)
                    {
                        hull.RemoveAt(hull.Count - 1);
                    }

                    hull.Add(point);
                }

                hull.RemoveAt(hull.Count - 1);
                sorted.Reverse();
            }

            return hull;
        }

        private static float Cross(Vector3 origin, Vector3 a, Vector3 b)
        {
            return (a.x - origin.x) * (b.z - origin.z) - (a.z - origin.z) * (b.x - origin.x);
        }

        private static float FlatDistance(Vector3 a, Vector3 b)
        {
            return Vector2.Distance(new Vector2(a.x, a.z), new Vector2(b.x, b.z));
        }

        private static void AddUpwardQuad(List<Vector3> vertices, List<int> triangles, Vector3 a, Vector3 b, Vector3 c, Vector3 d)
        {
            int index = vertices.Count;
            vertices.Add(a);
            vertices.Add(b);
            vertices.Add(c);
            vertices.Add(d);
            // Unity front faces are clockwise seen from the normal side (+Y).
            bool clockwiseFromAbove = Vector3.Cross(b - a, c - a).y > 0f;
            if (clockwiseFromAbove)
            {
                triangles.AddRange(new[] { index, index + 1, index + 2, index + 2, index + 1, index + 3 });
            }
            else
            {
                triangles.AddRange(new[] { index, index + 2, index + 1, index + 2, index + 3, index + 1 });
            }
        }

        private static (Material sidewalk, Material marking) ResolveMaterials()
        {
            Material sidewalk = null;
            Material marking = null;
            SumoRoadNetworkImporter importer = Object.FindFirstObjectByType<SumoRoadNetworkImporter>();
            if (importer != null)
            {
                SerializedObject properties = new SerializedObject(importer);
                sidewalk = properties.FindProperty("sidewalkMaterial").objectReferenceValue as Material;
                marking = properties.FindProperty("laneMarkingMaterial").objectReferenceValue as Material;
            }

            Shader shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
            if (sidewalk == null)
            {
                sidewalk = new Material(shader) { color = new Color(0.48f, 0.48f, 0.46f) };
            }

            if (marking == null)
            {
                marking = new Material(shader) { color = new Color(0.95f, 0.93f, 0.82f) };
            }

            return (sidewalk, marking);
        }

        private static void CreateMeshObject(string objectName, Mesh mesh, Material material, Transform parent)
        {
            GameObject gameObject = new GameObject(objectName);
            gameObject.transform.SetParent(parent, false);
            gameObject.AddComponent<MeshFilter>().sharedMesh = mesh;
            gameObject.AddComponent<MeshRenderer>().sharedMaterial = material;
        }
    }
}
